// 'XRP': {label:'转账TAG'},
// 					'BUC': {label:'paymentId'},
// 					'XRM': {label:'paymentId'},
// 					'BTS': {label:'转账备注'},
// 					'FLC': {label:'转账备注'},
// 					'XBC': {label:'MEMO'},
// 					'EOS': {label:'MEMO'},
const Coin={
    'BTC':{icon:'https://cdn.mytoken.org/e04064b7f151008854f4f0d6c822b608',code:'bitcoin',name:'Bitcoin'},
    'XRP':{icon:'https://cdn.mytoken.org/b806b2b93e583eca434a02008ae35f33',code:'ripple',name:'Ripple',label:'转账TAG'},
    'ETH':{icon:'https://cdn.mytoken.org/FvKK2xxE7DNqbKHA9Dle2FPheJJe',code:'ethereum',name:'Ethereum'},
    'ARN':{icon:'https://s1.feixiaohao.com/coin/20181030_72_png/aeron_200_200.png',code:'aeron',name:'Aeron'},
    'FQC':{icon:'https://cdn.mytoken.org/FvKK2xxE7DNqbKHA9Dle2FPheJJe',code:'FQCCoin',name:'FQCCoin'},
    'SMTH':{icon:'/static/images/coin/smth.png',code:'sthblock',name:'Smart Home'},
    'HLC':{icon:'https://s.zb.cn/statics/img/v3/coin/coin-hlc.png',code:'halalchain',name:'Halalchain'},
    'BCH':{icon:'https://cdn.mytoken.org/FvZPoFqN3D7ghXaPMI21vcH6Rd1s',code:'bitcoin-cash',name:'Bitcoin-cash'},
    'ELF':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2299.png',code:'aelf',name:'ELF'},
    'PPT':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1789.png',code:'populous',name:'Populous'},
    'HOT':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2682.png',code:'holo',name:'Holo'},
    'MTH':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1947.png',code:'monetha',name:'Monetha'},
    'QKC':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2840.png',code:'quarkchain',name:'QuarkChain'},
    'GTO':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2289.png',code:'gifto',name:'Gifto'},
    'MANA':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1966.png',code:'decentraland',name:'Decentraland'},
    'WABI':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2267.png',code:'wabi',name:'WaBi'},
    'WTC':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1925.png',code:'waltonchain',name:'Waltonchain'},
    'DOCK':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2675.png',code:'dock',name:'Dock'},
    'GVT':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2181.png',code:'genesis-vision',name:'Genesis Vision'},
    'DATA':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2143.png',code:'streamr-datacoin',name:'Streamr DATAcoin'},
    'XLM':{icon:'https://cdn.mytoken.org/519cdbf07cd778f982994c8132cc9865',code:'stellar',name:'Stellar'},
    'EOS':{icon:'https://cdn.mytoken.org/FjMXTFsqGTqS3rNEygtKl6BeBJeY',code:'eos',name:'EOS',label:'MEMO'},
    'XBC':{icon:'https://cdn.mytoken.org/FjMXTFsqGTqS3rNEygtKl6BeBJeY',code:'xbc',name:'Xbrick Coin',label:'MEMO'},
    'FLC':{icon:'https://cdn.mytoken.org/FjMXTFsqGTqS3rNEygtKl6BeBJeY',code:'flc',name:'Flashchain',label:'转账备注'},
    'XMR':{icon:'https://cdn.mytoken.org/a654ceec9011a417d48ec2388f0c2e6f',code:'monero',name:'Monero',label:'paymentId'},
    'BUC':{icon:'https://cdn.mytoken.org/a654ceec9011a417d48ec2388f0c2e6f',code:'buc',name:'bucmart',label:'paymentId'},
    'ADA':{icon:'https://cdn.mytoken.org/e7f4b8f7f40dd261a2d566fe00d96a27',code:'cardano',name:'Cardano'},
    'LTC':{icon:'https://cdn.mytoken.org/f216d6148b3e959cc8993dfe432647ee',code:'litecoin',name:'Litecoin'},
    'USDT':{icon:'https://cdn.mytoken.org/tether.png',code:'tether',name:'Tether',id:'49674'},
    'LRC':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1934.png',code:'loopring',name:'Loopring'},
    'AION':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2062.png',code:'aion',name:'Aion'},
    'REP':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1104.png',code:'augur',name:'Augur'},
    'WAN':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2606.png',code:'wanchain',name:'Wanchain'},
    'BCHSV':{icon:'https://cdn.mytoken.org/Fu_xo0ScQ8xOQQbzZwhtfgmf-Bo5',code:'bitcoin-cash-sv',name:'BitcoinSV'},
    'TRX':{icon:'https://cdn.mytoken.org/4c08d7948d080fc77b361777c5af4b10',code:'tron',name:'TRON'},
    'MIOTA':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/iota',code:'iota',name:'IOTA'},
    'DASH':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/dash.png',code:'dash',name:'Dash'},
    'XEM':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/nem',code:'nem',name:'NEM'},
    'BNB':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/binance-coin',code:'binance-coin',name:'Binance Coin'},
    'ETC':{icon:'https://cdn.mytoken.org/FkEEBMmwkrCw4G6acf9O48G2VY2T',code:'ethereum-classic',name:'Ethereum Classic'},
    'NEO':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/neo',code:'neo',name:'NEO'},
    'ONT':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/ontology',code:'ontology',name:'Ontology'},
    'ZEC':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/zcash',code:'zcash',name:'Zcash'},
    'XTZ':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/tezos.png',code:'tezos',name:'Tezos'},
    'BTG':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/bitcoin-gold',code:'bitcoin-gold',name:'Bitcoin Gold'},
    'VET':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/vet',code:'vet',name:'VeChain'},
    'MKR':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/maker.png',code:'maker',name:'Maker'},
    'HT':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/huobi-token',code:'huobi-token',name:'Huobi Token'},
    'DOGE':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/dogecoin',code:'dogecoin',name:'Dogecoin'},
    'OKB':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/okb',code:'okb',name:'OKB'},
    'OMG':{icon:'https://s1.feixiaohao.com/coin/20181030_72_png/omisego_200_200.png',code:'omisego',name:'OmiseGO'},
    'ZRX':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1896.png',code:'0x',name:'0x'},
    'TUSD':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/2563.png',code:'trueusd',name:'TrueUSD'},
    'DCR':{icon:'https://s1.feixiaohao.com/coin/20181030_72_png/decred_200_200.png',code:'decred',name:'Decred'},
    'QTUM':{icon:'https://s.zb.cn/statics/img/v3/coin/coin-qtum.png',code:'qtum',name:'Qtum'},
    'BAT':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/1697.png',code:'basic-attention-token',name:'Basic Attention Token'},
    'USDC':{icon:'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',code:'usd-coin',name:'USD Coin'},
    'LSK':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/lisk.png',code:'lisk',name:'Lisk'},
    'BCD':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/bitcoin-diamond',code:'bitcoin-diamond',name:'Bitcoin Diamond'},
    'BCN':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/bytecoin-bcn',code:'bytecoin-bcn',name:'Bytecoin'},
    'DGB':{icon:'https://blockchains.oss-cn-shanghai.aliyuncs.com/static/coinInfo/digibyte',code:'digibyte',name:'DigiByte'},
    'NANO':{icon:'https://cdn.mytoken.org/FjwqDmfsWM9HtfyCOpcokwX4hl8Y',code:'nano',name:'Nano'},
    'AE':{icon:'https://cdn.mytoken.org/Fu7PHI9jOBRz2bFnc09Qo2MG2Eav',code:'aeternity',name:'Aeternity'},
    'PAX':{icon:'https://cdn.mytoken.org/Frr7C-GfIhtf51XOB8K8BIKeWXHQ',code:'paxos-standard',name:'Paxos Standard'},
    'BTS':{icon:'https://cdn.mytoken.org/Fo5Syh3cIHTRHQ9uRcPMbcBtVZ-P',code:'bitshares',name:'BitShares',label:'转账备注'},
    'AOA':{icon:'https://cdn.mytoken.org/Fofz27q5QYlWn69Jm8CY4wq7P1it',code:'aurora',name:'Aurora'},
    'ZIL':{icon:'https://cdn.mytoken.org/FkyROESe5wy9rAw_tYUsyCCeiNID',code:'zilliqa',name:'Zilliqa'},
    'ICX':{icon:'https://cdn.mytoken.org/FlICEhVLPpIwPNDd8Hi_PA4XHEKu',code:'icon',name:'ICON'},
    'SC':{icon:'https://cdn.mytoken.org/Fr_rMLn946zcJ16hS-HR4K3ShBql',code:'siacoin',name:'Siacoin'},
    'LINK':{icon:'https://cdn.mytoken.org/0e3ed62447707537472d369d9bf5e347',code:'chainlink',name:'Chainlink'},
    'WAVES':{icon:'https://cdn.mytoken.org/FvwEOjrkm14JLAymoACsigRFNJeR',code:'waves',name:'Waves'},
    'STEEM':{icon:'https://cdn.mytoken.org/FiPYAuGQod6GttnWE87Y2nBk2cuE',code:'steem',name:'Steem'},
    'BTM':{icon:'https://cdn.mytoken.org/FubiSzIgMv7Aj2suu8dbNEUeSYu-',code:'bytom',name:'Bytom'},
}

export default Coin